# Project info
site_name: Arctic
site_url: https://github.com/manahl/arctic
site_description: High performance datastore for numeric data

# Repository info
repo_name: 'arctic'
repo_url: 'https://github.com/manahl/arctic'
edit_uri: edit/master/docs/

theme:
  name: 'readthedocs'

plugins:
    - search
